"""Document export tests."""

from __future__ import annotations

import pytest

from aiops_docproc import (
    Document,
    DocumentSection,
    ExportFormat,
    HtmlExporter,
    MarkdownExporter,
    PdfExporter,
    available_formats,
    get_exporter,
)
from aiops_utils import ConfigurationError, ValidationError


def _document() -> Document:
    return Document(
        title="Booking Delay Escalation SOP",
        subtitle="Operations — flight disruption handling",
        metadata={"Owner": "Ops Lead", "Version": "1.0", "Status": "Draft"},
        sections=[
            DocumentSection(
                heading="Purpose",
                body="Standardise how flight delays reach affected agents.",
                bullets=["Reduce response time", "Ensure consistent messaging"],
            )
        ],
        footer="Generated by the AI Operations Toolkit. Demo data only.",
    )


def test_markdown_export_contains_the_content() -> None:
    output = MarkdownExporter().render(_document()).decode("utf-8")
    assert "# Booking Delay Escalation SOP" in output
    assert "## Purpose" in output
    assert "- Reduce response time" in output
    assert "**Owner:** Ops Lead" in output


def test_html_export_escapes_user_content() -> None:
    """A section title from an untrusted source must not become live markup."""
    document = Document(
        title="Report <script>alert('xss')</script>",
        sections=[DocumentSection(heading="A & B", body="1 < 2")],
    )
    output = HtmlExporter().render(document).decode("utf-8")

    assert "<script>" not in output
    assert "&lt;script&gt;" in output
    assert "A &amp; B" in output


def test_markdown_and_html_are_always_available() -> None:
    formats = available_formats()
    assert ExportFormat.MARKDOWN in formats
    assert ExportFormat.HTML in formats


def test_pdf_availability_is_reported_honestly() -> None:
    """Either PDF works, or asking for it explains exactly what to install."""
    if PdfExporter.is_available():
        assert ExportFormat.PDF in available_formats()
        assert PdfExporter().render(_document()).startswith(b"%PDF")
    else:
        assert ExportFormat.PDF not in available_formats()
        with pytest.raises(ConfigurationError, match="WeasyPrint"):
            PdfExporter().render(_document())


def test_get_exporter_by_name() -> None:
    assert isinstance(get_exporter("markdown"), MarkdownExporter)
    assert isinstance(get_exporter(ExportFormat.HTML), HtmlExporter)


def test_unknown_format_is_rejected() -> None:
    with pytest.raises(ValidationError, match="Unsupported export format"):
        get_exporter("powerpoint")


def test_empty_document_still_renders() -> None:
    output = MarkdownExporter().render(Document(title="Empty")).decode("utf-8")
    assert "# Empty" in output
